{
  imports = [
    ./base-graphical
    ./base-server
    ./users
    ./boot.nix
    ./gpg.nix
    ./home-manager.nix
    ./misc.nix
    ./nginx.nix
    ./nix.nix
    ./openssh.nix
    ./packages.nix
    ./sanoid.nix
    ./security.nix
    ./steam.nix
    ./tailscale.nix
  ];
}
